server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: educagestor-api
    
  datasource:
    url: jdbc:postgresql://localhost:5432/educagestor_db
    username: ${DB_USERNAME:educagestor_user}
    password: ${DB_PASSWORD:educagestor_pass}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
    
  sql:
    init:
      mode: always
      
  security:
    user:
      name: admin
      password: admin123

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# Logging Configuration
logging:
  level:
    com.educagestor: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/educagestor-api.log

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true

# CORS Configuration
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:3001
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Pagination defaults
pagination:
  default-page-size: 20
  max-page-size: 100
